// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelPlanner.FlightService.Data;

#nullable disable

namespace TravelPlanner.FlightService.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    partial class FlightDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelPlanner.FlightService.Models.FlightRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FlightRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenities = "In-flight Entertainment,Meals,WiFi",
                            ArrivalTime = new DateTime(2025, 11, 17, 9, 54, 41, 735, DateTimeKind.Local).AddTicks(217),
                            AvailableSeats = 120,
                            Class = "Economy",
                            Currency = "EUR",
                            DepartureTime = new DateTime(2025, 11, 17, 7, 39, 41, 735, DateTimeKind.Local).AddTicks(188),
                            Duration = "1h 15m",
                            FlightNumber = "BA308",
                            From = "London Heathrow (LHR)",
                            Price = 89.99m,
                            Provider = "British Airways",
                            RouteId = "FL-042",
                            To = "Paris Charles de Gaulle (CDG)"
                        },
                        new
                        {
                            Id = 2,
                            Amenities = "Lie-flat Seats,Gourmet Meals,Premium Entertainment,WiFi",
                            ArrivalTime = new DateTime(2025, 11, 17, 20, 54, 41, 735, DateTimeKind.Local).AddTicks(228),
                            AvailableSeats = 85,
                            Class = "Business",
                            Currency = "GBP",
                            DepartureTime = new DateTime(2025, 11, 17, 11, 24, 41, 735, DateTimeKind.Local).AddTicks(227),
                            Duration = "6h 30m",
                            FlightNumber = "EK018",
                            From = "Manchester Airport (MAN)",
                            Price = 450.00m,
                            Provider = "Emirates",
                            RouteId = "FL-187",
                            To = "Dubai International (DXB)"
                        },
                        new
                        {
                            Id = 3,
                            Amenities = "In-flight Entertainment,Snacks,WiFi",
                            ArrivalTime = new DateTime(2025, 11, 17, 11, 54, 41, 735, DateTimeKind.Local).AddTicks(235),
                            AvailableSeats = 150,
                            Class = "Economy",
                            Currency = "USD",
                            DepartureTime = new DateTime(2025, 11, 17, 5, 24, 41, 735, DateTimeKind.Local).AddTicks(233),
                            Duration = "5h 30m",
                            FlightNumber = "DL302",
                            From = "New York JFK (JFK)",
                            Price = 220.00m,
                            Provider = "Delta Airlines",
                            RouteId = "FL-293",
                            To = "Los Angeles (LAX)"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
