// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelPlanner.BusService.Data;

#nullable disable

namespace TravelPlanner.BusService.Migrations
{
    [DbContext(typeof(BusDbContext))]
    partial class BusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelPlanner.BusService.Models.BusRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenities = "WiFi,Power Outlets,Toilet",
                            ArrivalTime = new DateTime(2025, 11, 17, 13, 51, 36, 378, DateTimeKind.Local).AddTicks(850),
                            AvailableSeats = 28,
                            Currency = "EUR",
                            DepartureTime = new DateTime(2025, 11, 17, 5, 21, 36, 378, DateTimeKind.Local).AddTicks(832),
                            Duration = "8h 30m",
                            From = "London Victoria Coach Station",
                            Price = 35.00m,
                            Provider = "FlixBus",
                            RouteId = "BUS-315",
                            To = "Paris Gallieni"
                        },
                        new
                        {
                            Id = 2,
                            Amenities = "WiFi,USB Charging",
                            ArrivalTime = new DateTime(2025, 11, 17, 9, 6, 36, 378, DateTimeKind.Local).AddTicks(858),
                            AvailableSeats = 35,
                            Currency = "GBP",
                            DepartureTime = new DateTime(2025, 11, 17, 6, 21, 36, 378, DateTimeKind.Local).AddTicks(857),
                            Duration = "2h 45m",
                            From = "Manchester",
                            Price = 15.00m,
                            Provider = "National Express",
                            RouteId = "BUS-428",
                            To = "Birmingham"
                        },
                        new
                        {
                            Id = 3,
                            Amenities = "WiFi,Power Outlets,Toilet",
                            ArrivalTime = new DateTime(2025, 11, 17, 11, 51, 36, 378, DateTimeKind.Local).AddTicks(862),
                            AvailableSeats = 42,
                            Currency = "USD",
                            DepartureTime = new DateTime(2025, 11, 17, 7, 21, 36, 378, DateTimeKind.Local).AddTicks(861),
                            Duration = "4h 30m",
                            From = "New York Port Authority",
                            Price = 25.00m,
                            Provider = "Greyhound",
                            RouteId = "BUS-512",
                            To = "Boston South Station"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
