// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelPlanner.TrainService.Data;

#nullable disable

namespace TravelPlanner.TrainService.Migrations
{
    [DbContext(typeof(TrainDbContext))]
    partial class TrainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelPlanner.TrainService.Models.TrainRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrainRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenities = "WiFi,Power Outlets,Refreshments",
                            ArrivalTime = new DateTime(2025, 11, 17, 8, 57, 38, 279, DateTimeKind.Local).AddTicks(2050),
                            AvailableSeats = 45,
                            Class = "Standard",
                            Currency = "EUR",
                            DepartureTime = new DateTime(2025, 11, 17, 6, 27, 38, 279, DateTimeKind.Local).AddTicks(2027),
                            Duration = "2h 30m",
                            From = "London St Pancras",
                            Price = 120.50m,
                            Provider = "Eurostar",
                            RouteId = "TR-001",
                            To = "Paris Gare du Nord"
                        },
                        new
                        {
                            Id = 2,
                            Amenities = "WiFi,Power Outlets,Refreshments",
                            ArrivalTime = new DateTime(2025, 11, 17, 8, 42, 38, 279, DateTimeKind.Local).AddTicks(2060),
                            AvailableSeats = 67,
                            Class = "Standard",
                            Currency = "GBP",
                            DepartureTime = new DateTime(2025, 11, 17, 4, 57, 38, 279, DateTimeKind.Local).AddTicks(2059),
                            Duration = "3h 45m",
                            From = "Manchester Piccadilly",
                            Price = 85.00m,
                            Provider = "Avanti West Coast",
                            RouteId = "TR-156",
                            To = "Edinburgh Waverley"
                        },
                        new
                        {
                            Id = 3,
                            Amenities = "WiFi,Power Outlets,Cafe Car",
                            ArrivalTime = new DateTime(2025, 11, 17, 10, 42, 38, 279, DateTimeKind.Local).AddTicks(2065),
                            AvailableSeats = 120,
                            Class = "Business",
                            Currency = "USD",
                            DepartureTime = new DateTime(2025, 11, 17, 7, 27, 38, 279, DateTimeKind.Local).AddTicks(2063),
                            Duration = "3h 15m",
                            From = "New York Penn Station",
                            Price = 98.00m,
                            Provider = "Amtrak",
                            RouteId = "TR-203",
                            To = "Washington DC Union Station"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
